### ISSUE TITLE
Please add QFN pin number to IO table

### ISSUE THREAD

**Issue by timsaxe** [QuickLogic-Corp/quick-feather-dev-board#1]
Symbiflow uses QFN pin numbers, not S3 IO numbers, so it would simplify creating pcf files if the IO table included QFN pin numbers as well as S3 IO numbers.

**Comment by anthonyle-ql** [comment]
Both the EOS S3 Datasheet and the QuickFeather User Guide has included the QFN pin #.

**Comment by anthonyle-ql** [comment]
refer to UG and DS for updated QFN information.
